title = "Brave Matrix"
baseurl = "https://bravematrix.org/"
languageCode = "en-us"
theme = "hugo-theme-blueberry-detox"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  Author = "AngeldsWang"
  disqusShortname = "angeldswang"
